"""Shared constants and dataclasses for the Lorentzian Classification CLI."""

from __future__ import annotations

import re
from dataclasses import dataclass

from .core import RESULT_FIELDNAMES, Settings


EXPORT_PACK_HEADER = "// Generated by lorentzian_classification export-pack"
SETTINGS_FINGERPRINT_COLUMN = "Settings Fingerprint"
SHA256_HEX_RE = re.compile(r"^[0-9a-f]{64}$")
DEBUG_MARKER_RE = re.compile(
    r"\b(?:debug|dbg_)\b|"
    r"\b(?:print|printf|printformat|comment|alert|console\.log)\s*\(",
    re.IGNORECASE,
)
external_PARITY_SCRIPT_INPUTS = {
    "InpInputFile": "input string",
    "InpOutputFile": "input string",
    "InpIncludeFullHist": "input bool",
}
external_PARITY_REPORT_COLUMNS = [
    "time",
    "close",
    "tv_f1",
    "external_f1",
    "f1_diff",
    "tv_f2",
    "external_f2",
    "f2_diff",
    "tv_f3",
    "external_f3",
    "f3_diff",
    "tv_f4",
    "external_f4",
    "f4_diff",
    "tv_f5",
    "external_f5",
    "f5_diff",
    "tv_kernel",
    "external_kernel",
    "kernel_diff",
    "tv_prediction",
    "external_prediction",
    "pred_match",
    "tv_direction",
    "external_direction",
    "dir_match",
    "tv_buy",
    "external_buy",
    "tv_sell",
    "external_sell",
]
external_FEATURE_ENUMS = {
    "RSI": "FEATURE_RSI",
    "WT": "FEATURE_WT",
    "CCI": "FEATURE_CCI",
    "ADX": "FEATURE_ADX",
}
EXPORT_PACK_ACCEPTANCE_FIELDNAMES = [
    "name",
    "target_csv",
    "helper_snippet",
    "helper_snippet_sha256",
    "status",
    "settings_fingerprint",
    "settings_fingerprint_column",
    "pine_source_lock_fingerprint",
    "required_full_export_column_count",
    "required_full_export_columns",
    "cli_flags",
    "settings_json",
    "proves",
]

PARITY_FIXTURES: tuple[tuple[str, bool], ...] = (
    ("pine_oanda_eurusd_1d_full_history.csv", True),
    ("pine_tastyfx_eurusd_1d_full_history.csv", True),
    ("pine_coinbase_btcusd_1d_limited_history.csv", False),
    ("pine_btcusd_h1_trimmed_limited_history.csv", False),
)
VALID_SOURCES = ("open", "high", "low", "close", "hl2", "hlc3", "ohlc4")
FEATURE_SLOTS = ("f1", "f2", "f3", "f4", "f5")
FEATURE_TYPES = ("RSI", "WT", "CCI", "ADX")
BOOLEAN_SETTING_FIELDS = {
    "include_full_history",
    "use_volatility_filter",
    "use_regime_filter",
    "use_adx_filter",
    "use_ema_filter",
    "use_sma_filter",
    "use_kernel_filter",
    "use_kernel_smoothing",
    "use_dynamic_exits",
    "show_exits",
    "use_worst_case",
    "show_kernel_estimate",
    "show_bar_colors",
    "show_bar_predictions",
    "use_atr_offset",
    "use_confidence_gradient",
    "show_trade_stats",
}
INTEGER_SETTING_FIELDS = {
    "neighbors_count",
    "max_bars_back",
    "feature_count",
    "color_compression",
    "adx_threshold",
    "ema_period",
    "sma_period",
    "kernel_h",
    "kernel_x",
    "kernel_lag",
}
FLOAT_SETTING_FIELDS = {"regime_threshold", "kernel_r", "bar_predictions_offset"}
PINE_SETTING_BOUNDS: dict[str, tuple[float | int | None, float | int | None]] = {
    "neighbors_count": (1, 100),
    "feature_count": (2, 5),
    "color_compression": (1, 10),
    "regime_threshold": (-10, 10),
    "adx_threshold": (0, 100),
    "ema_period": (1, None),
    "sma_period": (1, None),
    "kernel_h": (3, None),
    "bar_predictions_offset": (0, None),
}


@dataclass(frozen=True)
class ParityFixture:
    name: str
    filename: str
    settings: Settings
    tolerance: float | None = None


@dataclass(frozen=True)
class PineSourceSpec:
    name: str
    path: str
    role: str
    sha256: str | None = None
    code_sha256: str | None = None
    allow_debug_markers: bool = True


@dataclass(frozen=True)
class externalParityReportSpec:
    name: str
    filename: str
    role: str
    input_filename: str
    include_full_history: bool
    script_path: str = "Scripts/LorentzianParityCheck.external_src"
    required: bool = True
    tolerance: float | None = None


MINIMUM_PINE_EXPORT_COLUMNS = [
    "time",
    "open",
    "high",
    "low",
    "close",
    "F1_RSI",
    "F2_WT",
    "F3_CCI",
    "F4_ADX",
    "F5_RSI9",
    "Kernel Regression Estimate",
    "Prediction",
    "Direction",
    "Buy",
    "Sell",
    "StopBuy",
    "StopSell",
]

DEFAULT_FEATURE_EXPORT_COLUMNS = {
    1: "F1_RSI",
    2: "F2_WT",
    3: "F3_CCI",
    4: "F4_ADX",
    5: "F5_RSI9",
}

PINE_PREDICTION_TRANSPARENCY_EXPR = (
    "(useConfidenceGradient ? "
    "(math.min(math.abs(prediction), 10) >= 9 ? 0 : "
    "math.min(math.abs(prediction), 10) >= 8 ? 10 : "
    "math.min(math.abs(prediction), 10) >= 7 ? 20 : "
    "math.min(math.abs(prediction), 10) >= 6 ? 30 : "
    "math.min(math.abs(prediction), 10) >= 5 ? 40 : "
    "math.min(math.abs(prediction), 10) >= 4 ? 50 : "
    "math.min(math.abs(prediction), 10) >= 3 ? 60 : "
    "math.min(math.abs(prediction), 10) >= 2 ? 70 : "
    "math.min(math.abs(prediction), 10) >= 1 ? 80 : 90) : 0)"
)

PINE_EXPORT_SERIES = [
    {"column": "time", "pine_expression": "time", "export_mode": "chart_export_builtin"},
    {"column": "open", "pine_expression": "open", "export_mode": "chart_export_builtin"},
    {"column": "high", "pine_expression": "high", "export_mode": "chart_export_builtin"},
    {"column": "low", "pine_expression": "low", "export_mode": "chart_export_builtin"},
    {"column": "close", "pine_expression": "close", "export_mode": "chart_export_builtin"},
    {"column": "F1_RSI", "pine_expression": "featureSeries.f1", "export_mode": "plot_data_window"},
    {"column": "F2_WT", "pine_expression": "featureSeries.f2", "export_mode": "plot_data_window"},
    {"column": "F3_CCI", "pine_expression": "featureSeries.f3", "export_mode": "plot_data_window"},
    {"column": "F4_ADX", "pine_expression": "featureSeries.f4", "export_mode": "plot_data_window"},
    {"column": "F5_RSI9", "pine_expression": "featureSeries.f5", "export_mode": "plot_data_window"},
    {
        "column": "Kernel Regression Estimate",
        "pine_expression": "kernelEstimate",
        "export_mode": "plot_or_plot_data_window",
    },
    {"column": "Prediction", "pine_expression": "prediction", "export_mode": "plot_data_window"},
    {
        "column": "Direction",
        "pine_expression": "signal == direction.long ? 1 : signal == direction.short ? -1 : 0",
        "export_mode": "plot_data_window",
    },
    {"column": "Buy", "pine_expression": "startLongTrade ? 1 : na", "export_mode": "plot_data_window"},
    {"column": "Sell", "pine_expression": "startShortTrade ? 1 : na", "export_mode": "plot_data_window"},
    {
        "column": "StopBuy",
        "pine_expression": "endLongTrade and settings.showExits ? 1 : na",
        "export_mode": "plot_data_window",
    },
    {
        "column": "StopSell",
        "pine_expression": "endShortTrade and settings.showExits ? 1 : na",
        "export_mode": "plot_data_window",
    },
    {"column": "Backtest Stream", "pine_expression": "backTestStream", "export_mode": "plot_data_window"},
    {
        "column": "Open Long Alert",
        "pine_expression": "startLongTrade ? 1 : 0",
        "export_mode": "plot_data_window",
    },
    {
        "column": "Close Long Alert",
        "pine_expression": "endLongTrade ? 1 : 0",
        "export_mode": "plot_data_window",
    },
    {
        "column": "Open Short Alert",
        "pine_expression": "startShortTrade ? 1 : 0",
        "export_mode": "plot_data_window",
    },
    {
        "column": "Close Short Alert",
        "pine_expression": "endShortTrade ? 1 : 0",
        "export_mode": "plot_data_window",
    },
    {
        "column": "Open Position Alert",
        "pine_expression": "startShortTrade or startLongTrade ? 1 : 0",
        "export_mode": "plot_data_window",
    },
    {
        "column": "Close Position Alert",
        "pine_expression": "endShortTrade or endLongTrade ? 1 : 0",
        "export_mode": "plot_data_window",
    },
    {
        "column": "Kernel Bullish Alert",
        "pine_expression": "alertBullish ? 1 : 0",
        "export_mode": "plot_data_window",
    },
    {
        "column": "Kernel Bearish Alert",
        "pine_expression": "alertBearish ? 1 : 0",
        "export_mode": "plot_data_window",
    },
    {
        "column": "Prediction Label Y",
        "pine_expression": "y_val",
        "export_mode": "plot_data_window",
    },
    {"column": "Total Wins", "pine_expression": "totalWins", "export_mode": "plot_data_window"},
    {"column": "Total Losses", "pine_expression": "totalLosses", "export_mode": "plot_data_window"},
    {
        "column": "Total Early Signal Flips",
        "pine_expression": "totalEarlySignalFlips",
        "export_mode": "plot_data_window",
    },
    {"column": "Total Trades", "pine_expression": "totalTrades", "export_mode": "plot_data_window"},
    {"column": "Win Loss Ratio", "pine_expression": "winLossRatio", "export_mode": "plot_data_window"},
    {"column": "Table WL Ratio", "pine_expression": "totalWins / totalLosses", "export_mode": "plot_data_window"},
    {"column": "Win Rate", "pine_expression": "winRate", "export_mode": "plot_data_window"},
    {
        "column": "Trade Stats Visible",
        "pine_expression": "showTradeStats ? 1 : 0",
        "export_mode": "plot_data_window",
    },
    {
        "column": "Kernel Plot Color",
        "pine_expression": (
            "showKernelEstimate ? "
            "(useKernelSmoothing ? (isBullishSmooth ? 120 : -120) : (isBullishRate ? 120 : -120)) : 0"
        ),
        "export_mode": "encoded_plot_data_window",
        "note": "Numeric code decoded by Python: 120=#009988@20, -120=#CC3311@20, 0=#000000@100.",
    },
    {
        "column": "Prediction Label",
        "pine_expression": "prediction",
        "export_mode": "encoded_plot_data_window",
        "note": "Numeric prediction decoded by Python as the label text.",
    },
    {
        "column": "Prediction Label Color",
        "pine_expression": (
            "showBarPredictions ? "
            f"(prediction > 0 ? 100 + {PINE_PREDICTION_TRANSPARENCY_EXPR} : "
            f"prediction < 0 ? -100 - {PINE_PREDICTION_TRANSPARENCY_EXPR} : 225) : na"
        ),
        "export_mode": "encoded_plot_data_window",
        "note": "Numeric code decoded by Python to the Pine label color.",
    },
    {
        "column": "Bar Color",
        "pine_expression": (
            "showBarColors ? "
            "(prediction > 0 ? 100 + (useConfidenceGradient ? 50 : 30) : "
            "prediction < 0 ? -100 - (useConfidenceGradient ? 50 : 30) : "
            "200 + (useConfidenceGradient ? 50 : 30)) : na"
        ),
        "export_mode": "encoded_plot_data_window",
        "note": "Numeric code decoded by Python to the Pine bar color.",
    },
    {
        "column": "Trade Stats Header",
        "pine_expression": "1",
        "export_mode": "encoded_plot_data_window",
        "note": "Numeric code 1 decoded by Python as the fixed Pine trade-stats header.",
    },
]
